config/routes.rb
ForUncle::Application.routes.draw do
  
  

  resources :sellers

  resources :clients do
    resources :operations, only: [:create, :destroy]
  end
  root :to => 'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signup',  to: 'clients#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'

  

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :credit_limit, :name
  has_many :operations, dependent: :destroy

  validates :credit_limit, presence: true
  validates :name, presence: true
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  belongs_to :client
  attr_accessible :coment, :value

  validates :client_id, presence: true
  validates :value, presence: true, numericality: { only_integer: true }
  default_scope order: 'operations.created_at DESC'
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation
  has_secure_password

  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  

  private
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/clients_controller.rb
# encoding: utf-8
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.paginate(page: params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
    @operations = @client.operations.paginate(page: params[:page])
    @operation = @client.operations.build(params[:operation])
    @current_credit = @client.credit_limit - @client.operations.map {|i| i.value.to_i }.inject(0){|result, elem| result + elem }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        flash[:success] = "Ура, клиент добавлен!"
        format.html { redirect_to @client }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/operations_controller.rb
# encoding: utf-8
class OperationsController < ApplicationController
  
  before_filter :correct_client


  # POST /operations
  # POST /operations.json
  def create
    @operation = @client.operations.build(params[:operation])
    
    respond_to do |format|
      if @operation.save
        flash[:success] = "Операция совершена"
        format.html { redirect_to @client }
      else
        @feed_items = []
        flash[:error] = "Неправильно введена сумма."
        format.html { redirect_to @client }
      end
    end
  end


  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation = Operation.find(params[:id])
    @operation.destroy

    respond_to do |format|
      format.html { render clients_path }
      format.json { head :no_content }
    end
  end

  private

    def correct_client
      @client = Client.find(params[:client_id])
    end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  
  before_filter :signed_in_seller, only: [:show, :edit, :update, :destroy]
  before_filter :correct_seller,   only: [:edit, :update]
  before_filter :seller_admin,     only: [:edit, :update, :destroy]
  
  def index
    @sellers = Seller.all
  end

  def show
    @seller = Seller.find(params[:id])  
    @feed_items = Operation.paginate(page: params[:page])
  end

  def new
    @seller = Seller.new
  end

  def create
    @seller = Seller.new(params[:seller])    
    if @seller.save
      sign_in @seller
      flash[:success] = "Welcome"
      redirect_to @seller
    else
      render 'new'
    end
  end

  def edit
    @seller = Seller.find(params[:id])
  end

  def update
    @seller = Seller.find(params[:id])
    if @seller.update_attributes(params[:seller])
      sign_in @seller
      flash[:success] = "Profile updated"
      redirect_to @seller
    else
      render 'edit'
    end
  end

  def destroy
    Seller.find(params[:id]).destroy
    flash[:success] = "Seller destroyed"
    redirect_to sellers_url
  end

  private

    def correct_seller
      @seller = Seller.find(params[:id])
      redirect_to root_path unless current_seller?(@seller)
    end

    def seller_admin
      redirect_to(root_path) unless current_seller.admin?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    seller = Seller.find_by_name(params[:session][:name])
    if seller && seller.authenticate(params[:session][:password])
      sign_in seller
      redirect_back_or seller
    else
      flash.now[:error] = "Invalid"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      redirect_to clients_path
    end
  end

  def help
  end

  def about
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "For Uncle"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end    
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
  
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(seller)
    cookies.permanent[:remember_token] = seller.remember_token
    current_seller = seller  
  end

  def signed_in?
    !current_seller.nil?    
  end
  
  def signed_in_seller
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end

  def feed
    Operation.all
  end
  
  def sign_out
    current_seller = nil
    cookies.delete(:remember_token)
  end
  
  def current_seller=(seller)
    @current_seller = seller
  end

  def current_seller
    @current_seller ||= seller_from_remember_token
  end

  def current_seller?(seller)
    seller == current_seller    
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)    
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def admin?(seller)
    current_seller.admin == seller
  end
  private

    def seller_from_remember_token
      remember_token = cookies[:remember_token]
      Seller.find_by_remember_token(remember_token) unless remember_token.nil?      
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clients/_client.html.haml
%li
  = link_to client.name, client 
  - if signed_in?
    - if current_seller.admin?
      \|
      = link_to "delete", client, method: :delete, data: { confirm: "Вы уверены?" } 

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <%= render 'shared/error_messages', object: f.object%>
    

  <div class="field">
    <%= f.label :name, "Имя" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :credit_limit, "Лимит кредита" %><br />
    <%= f.text_field :credit_limit %>
  </div>
  <div class="actions">
    <%= f.submit "Добавить клиента", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Back', @client %>

app/views/clients/index.html.erb
<% provide(:title, 'About Us') %>


<h1>Список клиентов</h1>
<%= link_to 'New Client', new_client_path %>
<%= will_paginate %>
<ul>
  <%= render @clients %>
</ul>
<%= will_paginate %>
<br />

app/views/clients/new.html.erb
<h1>Новый клиент</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.haml
- provide(:title, @client.name)
%section  
  %header
    .row
      .span
        - if current_seller
          %h3 Продавец: #{link_to current_seller.name, current_seller}
          - if current_seller.admin?
            = link_to 'Edit', edit_client_path(@client)
            |
            =link_to 'Back', clients_path
      .span.pull-right
        %h3 Лимит долга: #{@client.credit_limit}
        %br
        
%br
%h2 ФИО клиента: #{@client.name}
%section
  = render 'operations/form'
  .row-fluid
    .span4
    .span8
      %table
        %thead
          %tr
            %th Сумма
            %th Примечание
            %th Время и дата покупки
        %tbody
          
          = render @operations
          = will_paginate @operations

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "for uncle", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Главная", root_path %></li>
              <li><%= link_to "Помощь", help_path  %></li>
              <% if signed_in? %>
                <li><%= link_to "Продавцы", sellers_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= current_seller.name %> <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Профиль", current_seller %></li>
                    <li><%= link_to "Редактировать", edit_seller_path(current_seller) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Выйти", signout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li><%= link_to "Войти", signin_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      
    </div>
  </body>
</html>

app/views/operations/_form.html.haml
.well 
  = form_for [@client, @operation] do |f|
    = render 'shared/error_messages', object: f.object
    .row-fluid
      .span2.field
        = f.label :value, "Сумма"
        = f.text_field :value
      .span6.field
        = f.label :coment, "Комментарий"
        = f.text_field :coment
      .span4.actions
        %b Остаток: #{@current_credit} рублей
        #ostatok
          = f.submit "Добавить операцию", class: "btn btn-primary"

app/views/operations/_operation.html.haml
%tr
  %td 
    = operation.value
  %td 
    = operation.coment
  %td 
    = operation.created_at.strftime("%k:%M %e  %B")
  / %td
  /   = link_to "delete", [@client, operation], method: :delete

app/views/sellers/_form.html.haml
= f.label :name
= f.text_field :name

= f.label :password
= f.password_field :password

= f.label :password_confirmation
= f.password_field :password_confirmation

app/views/sellers/_seller.html.haml
.row-fluid
  .span5
    = link_to seller.name, seller
  .span5
    - if current_seller != seller && current_seller.admin?
      = link_to "Удалить", seller, method: :delete, data: { confirm: "Вы уверены?" }

%br

app/views/sellers/edit.html.haml
= form_for @seller do |f|
  = render 'shared/error_messages', object: f.object
  = render 'form', f: f
  = f.submit "Обновить профиль", class: "btn btn-primary"

app/views/sellers/index.html.haml
= render @sellers
%br
= link_to "Добавить продавца", new_seller_path if current_seller.admin?

app/views/sellers/new.html.haml
- provide(:title, "Регистрация")
= form_for @seller do |f|
  = render 'form', f: f
  = render 'shared/error_messages', object: f.object
  = f.submit "Добавить продавца", class: "btn btn-primary"

app/views/sellers/show.html.haml
- provide(:title, @seller.name)
%h3 
  Продавец:
  = @seller.name
%section
  %ol.operations
    = render partial: 'shared/feed_item', collection: @feed_items 

  = will_paginate @feed_items

= link_to "Список клиентов", clients_path

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed_item.html.haml
%li.timestamp
  .row-fluid
    .span3
      .center= feed_item.value
    .span3
      = feed_item.client.name
    .span3
      = feed_item.coment.blank? ? "..." : feed_item.coment
    .sapn3
      = feed_item.created_at.strftime("%k:%M %e %B")
  

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>Пока ничего, но вскоре здесь появится куча всего интересного об авторе! :)</p>
 

app/views/static_pages/help.html.erb
<% provide(:title, 'Помощь') %>


<p>Сайт предназначен для ведения учета должников</p>

app/views/static_pages/home.html.haml
.row
  %section.pull-right
    .well
      = render 'sessions/form'
  %section
    %header
      %h1 Добро пожаловать!
    %section
      %article
        %h3 Вы можете посмотреть #{link_to "список клиентов", clients_path}, так же можете войти как продавец или администратор.
        %p Чтобы зайти как администратор введите "Титаренко Леонид" пароль-"123456"

/ = link_to "Список клиентов", clients_path, class: "btn btn-large btn-primary" 
/ = link_to "Список продавцов", sellers_path, class: "btn btn-large btn-primary" 